spring.application.name=producer-service
spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.bootstrap-servers=kafka:9092

# Producer Serializer Settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Allow Kafka to serialize any Java object to JSON
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Server Port
server.port=8081
