spring.application.name=gatewayApi

server.port=8080

# Route to Order Service (Port 8082)
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082/
spring.cloud.gateway.routes[0].predicates[0]=Path=/order/**

# Route to User Service (Port 8083)
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:8083/
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**

# Global Filters (for Logging)
spring.cloud.gateway.default-filters[0]=PrefixPath=/api